# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 18:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, default='', max_length=100)),
                ('crop_output', models.IntegerField()),
                ('cropfarm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_area', models.IntegerField()),
                ('farm_position', django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Info_Keys',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='House_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_capacity', models.IntegerField()),
                ('house_area', models.IntegerField()),
                ('house_income', models.IntegerField()),
                ('house_position', django.contrib.gis.db.models.fields.PointField(default='', srid=4326)),
                ('house_image', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House_Info_Keys',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_head', models.CharField(blank=True, default='', max_length=100)),
                ('village_name', models.CharField(blank=True, default='', max_length=100)),
                ('mail_id', models.CharField(blank=True, default='', max_length=100)),
                ('aadhar_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wells_Info',
            fields=[
                ('wellsinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('wells_position', django.contrib.gis.db.models.fields.PointField(default='', srid=4326)),
                ('wells_depth', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='house_info_keys',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.Personal_Info'),
        ),
        migrations.AddField(
            model_name='house_info',
            name='houseinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.House_Info_Keys'),
        ),
        migrations.AddField(
            model_name='farm_info_keys',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.Personal_Info'),
        ),
        migrations.AddField(
            model_name='farm_info',
            name='farminfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastorage.Farm_Info_Keys'),
        ),
    ]
